# Generated by Django 3.2.2 on 2021-05-17 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210517_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_disliked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='is_liked',
            field=models.BooleanField(default=False),
        ),
    ]
