# Generated by Django 3.2.2 on 2021-05-17 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210517_2244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='downvote_num',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='upvote_num',
        ),
        migrations.RemoveField(
            model_name='post',
            name='downvote_num',
        ),
        migrations.RemoveField(
            model_name='post',
            name='upvote_num',
        ),
        migrations.AddField(
            model_name='comment',
            name='balance',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comment',
            name='is_disliked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comment',
            name='is_liked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='balance',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
