# Generated by Django 3.2.2 on 2021-06-10 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210610_1824'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='is_disliked',
        ),
        migrations.RemoveField(
            model_name='post',
            name='is_liked',
        ),
    ]
