# Generated by Django 3.2.2 on 2021-05-18 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210517_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='balance',
            field=models.IntegerField(default=0),
        ),
    ]
